---
title: "Exploratory scratch program"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## GGPLOT practice


```{r cars}
library(lubridate)
library(taRifx)
library(lme4)
library(mclust)
library(network)
library(igraph)
#Don't forget to install in MakeFile


ls(IntraParticipants)


ls(Overall)

```
```{r cars}

#Pre-internationalized data set

ls(IntraParticipants)
IP=Overall


table(unique(IP$WarNum))

IP<-IP%>% mutate(WarTypeC = as.factor(case_when(
                           WarType==4~'Civil War: Central Control',WarType==5~'Civil War: Local Issues',WarType==6~'Regional Internal',WarType==7~'Intercommunal',WarType==-8~'NA' )),V5RegionC=case_when(V5RegionNum==1~'North America',V5RegionNum==2~'South America',V5RegionNum==3~'Europe',V5RegionNum==4~'Sub-Saharan Africa',V5RegionNum==5~'Middle East and North Africa',V5RegionNum==6~'Asia and Oceania'),OutcomeC=case_when(Outcome==1~"Side A wins",Outcome==2~"Side B wins",Outcome==3~"Compromise",Outcome==4~"War transformed into another War",Outcome==5~"War ongoing as of end of 2014",Outcome==6~"Stalemate",Outcome==7~"Conflict continues below war level" ) )

IP$WarTypeD=ifelse(IP$WarType==4,'Civil War: Central Control',ifelse(IP$WarType==5,'Civil War: Local Issues',ifelse(IP$WarType%in%c(6,7),'Other','NA')))


#Create initiator deaths Var (need to create war id long dataset)
#IP$InitiatorDeaths=ifelse(IP$Initiator==IP$SideA,IP$DeathsSideA,IP$DeathsSideB)
#IP$RecipientDeaths=ifelse(IP$Initiator==IP$SideB,IP$DeathsSideB,IP$DeathsSideA)

#Set upper limit to deaths 50000
IP$TotalBDeathsU=ifelse(IP$TotalBDeaths>=50000,50000,IP$TotalBDeaths)

#Make Hemisphere driven variable
IP$Americas=ifelse(IP$V5RegionNum %in% c(1,2),'Americas','Not in Americas')

#Let's make some dates

IP$Phase1_st=ymd( paste(IP$StartYr1, IP$StartMo1, IP$StartDy1, sep="-"))
IP$Phase2_st=ymd( paste(IP$StartYr2, IP$StartMo2, IP$StartDy2, sep="-"))
IP$Phase3_st=ymd( paste(IP$StartYr3, IP$StartMo3, IP$StartDy3, sep="-"))
IP$Phase4_st=ymd( paste(IP$StartYr4, IP$StartMo4, IP$StartDy4, sep="-"))

IP$Phase1_en=ymd( paste(IP$EndYr1, IP$EndMo1, IP$EndDy1, sep="-"))
IP$Phase2_en=ymd( paste(IP$EndYr2, IP$EndMo2, IP$EndDy2, sep="-"))
IP$Phase3_en=ymd( paste(IP$EndYr3, IP$EndMo3, IP$EndDy3, sep="-"))
IP$Phase4_en=ymd( paste(IP$EndYr4, IP$EndMo4, IP$EndDy4, sep="-"))



#Test data set two observations per war number for eventual modeling)%>%select(WarNum,TotalBDeaths,TotalBDeathsU,WDuratDays,Americas,WarTypeD,InitiatorDeaths,RecipientDeaths,DeathsSideA,DeathsSideB)

library(reshape2)

Sub1<-IP%>%mutate(deaths=DeathsSideA)%>%select(WarNum,deaths,WDuratDays,Americas,WarTypeD,Initiator,SideA)
Sub1$side='A'
Sub1$Init=ifelse(Sub1$SideA==Sub1$Initiator,1,0)
SubA<-Sub1%>%select(-c(Initiator,SideA))

Sub2<-IP%>%mutate(deaths=DeathsSideB)%>%select(WarNum,deaths,WDuratDays,Americas,WarTypeD,Initiator,SideB)
Sub2$side='B'
Sub2$Init=ifelse(Sub2$SideB==Sub2$Initiator,1,0)
SubB<-Sub2%>%select(-c(Initiator,SideB))


Long=data.frame(rbind(SubA,SubB))


#Transition variables (to and from)#Create dataset of wars spread out or transferred to another war
#Did counts below


#Look at descriptive attributes of those 


#Attempt clustering 


#Repeat above descriptive on wars that were internationalized


#Do Aim 1 GEE on the intra participants dataset



#Aim 2 will look to (cluster time) and add as variable in models



#Aim 3 Decision tree/network of internationalized war (attributes)



#Keep only IDs of WarNum, TransTo,TransFrom

chk<-IP%>%select(WarNum, TransTo,TransFrom)



#Overall dataset (Focus on descriptive statistics) Above


#Long dataset (two records per war ID) To do


#Dataset for wars which spread out to other wars To do



#Repeat for internationalized wars

```


```{r cars}

#Output Type of War
table(IP$WarTypeC)
#Output geographic region
table(IP$V5RegionC)
#Output outcome
table(IP$OutcomeC)

#Output Cross-tab of war type and region
table(IP$WarTypeC,IP$V5RegionC)
#Output Cross-tab of war type and outcome
table(IP$WarTypeC,IP$OutcomeC)
#Output Cross-tab of region and outcome
table(IP$V5RegionC,IP$OutcomeC)






#Practice plots

#Total exposure time (days)
ggplot(IP,aes(x=WDuratDays))+geom_histogram()+xlab('Total number of days war lasted')+ylab('Frequency')


#Total exposure time (months)
#ggplot(IP,aes(x=WDuratMo))+geom_histogram()+xlab('Total number of months war lasted')+ylab('Frequency')

#Total number of battle-related deaths both sides
ggplot(IP,aes(x=TotalBDeaths))+geom_histogram()+xlab('Total number of battle-related deaths both sides')+ylab('Frequency')

#Total deaths by war type
ggplot(IP,aes(y=TotalBDeathsU,x=WarTypeC))+geom_boxplot()+ylab('Upper limit greater than 50000 set to 50000 deaths')

#Total deaths by Region
ggplot(IP,aes(y=TotalBDeathsU,x=V5RegionC))+geom_boxplot()+ylab('Upper limit greater than 50000 set to 50000 deaths')+theme(axis.text.x = element_text(angle = 90))

#Total deaths by Americas
ggplot(IP,aes(y=TotalBDeathsU,x=Americas))+geom_boxplot()+ylab('Upper limit greater than 50000 set to 50000 deaths')

#Total deaths by Americas facet grid
ggplot(IP,aes(y=TotalBDeathsU,x=Americas))+geom_boxplot()+ylab('Upper limit greater than 50000 set to 50000 deaths')+facet_grid(~ WarTypeC)
ggplot(IP,aes(y=TotalBDeathsU,x=Americas))+geom_boxplot()+ylab('Upper limit greater than 50000 set to 50000 deaths')+facet_grid(~ WarTypeD)




#Initiator deaths Repeated above



#Recipient deaths repeated above





#Total deaths and exposure time (days) by war type
ggplot(IP, aes(TotalBDeathsU,WDuratDays)) + geom_point(aes(color=WarTypeD))
#Total deaths and exposure time (months) by war type
ggplot(IP, aes(TotalBDeathsU,WDuratMo)) + geom_point(aes(color=WarTypeD))

#Total deaths and exposure time (days) by region
ggplot(IP, aes(TotalBDeathsU,WDuratDays)) + geom_point(aes(color=V5RegionC))
#Total deaths and exposure time (months) by region
ggplot(IP, aes(TotalBDeathsU,WDuratMo)) + geom_point(aes(color=V5RegionC))


#Total deaths and exposure time (days) by Americas indicator
ggplot(IP, aes(TotalBDeathsU,WDuratDays)) + geom_point(aes(color=Americas))
#Total deaths and exposure time (months) by region
ggplot(IP, aes(TotalBDeathsU,WDuratMo)) + geom_point(aes(color=Americas))




#Temporal plots


#Deaths,war types, region by time

p1 <- ggplot(IP, 
        aes(x = StartYr1, y = TotalBDeathsU)) +
  geom_point()

p1

p2 <- ggplot(IP, 
        aes(x = StartYr1, y = TotalBDeathsU)) +
  geom_point()+facet_grid(~Americas)

p2


p3 <- ggplot(IP, 
        aes(x = StartYr1, y = TotalBDeathsU,group=WarTypeD,color=WarTypeD)) +
  geom_point()+facet_grid(~Americas)

p3


p1 <- ggplot(IP, 
        aes(x = StartYr1, y = TotalBDeathsU)) +
  geom_line()+facet_grid(~Americas)

p1


p1<-ggplot(IP, aes(x=Date,y= hms1))+ scale_x_date(breaks = date_breaks("1 day"))+
geom_linerange(aes(ymin = hms1, ymax = hms2),color = "red",size = 2)+ coord_flip()
p1+ylab("Time")+ggtitle("Activity During Day")

ggplot(IP, aes(x=StartYr1))  +
  scale_y_continuous(limits = c(0,10000), breaks=seq(0,10000,100))  +
  geom_linerange(aes(ymin = Phase1_st, ymax = Phase1_en), color = "red",size = 2) + 
  coord_flip() + ylab("Time (days)") + 
  ggtitle("War Activity across 2 centuries")


# ggplot(IP, aes(x=StartYr1)) + 
#   scale_x_datetime(breaks = date_breaks("1 day")) +
#   scale_y_continuous(limits = c(0,10000), breaks=seq(0,10000,100), 
#                      labels=str_pad(seq(0,10000,100) %% 24, 2, pad="0")) +
#   geom_hline(yintercept=seq(0,48,24)) +
#   geom_linerange(aes(ymin = hms1a - Date, ymax = hms2a - Date), color = "red",size = 2) + 
#   coord_flip() + ylab("Time (hours)") + 
#   ggtitle("Activity During Day")



#Take a look at number of wars that transferred to another war
Toanothewar=subset(IP,TransTo!=-8)
Toanothewar%>%summarize(count=n())

#Take a look at numer of wars transferred from another war
Fanothewar=subset(IP,TransFrom!=-8)
Fanothewar%>%summarize(count=n())


#Calculate time or break between phases 1, 2,3,4.  We want to look at total delayed time and attributes above




#GEE 
IP=IntraParticipants


table(unique(IP$WarNum))

IP<-IP%>% mutate(WarTypeC = as.factor(case_when(
                           WarType==4~'Civil War: Central Control',WarType==5~'Civil War: Local Issues',WarType==6~'Regional Internal',WarType==7~'Intercommunal',WarType==-8~'NA' )),V5RegionC=case_when(V5Region==1~'North America',V5Region==2~'South America',V5Region==3~'Europe',V5Region==4~'Sub-Saharan Africa',V5Region==5~'Middle East and North Africa',V5Region==6~'Asia and Oceania'),OutcomeC=case_when(Outcome==1~"Side A wins",Outcome==2~"Side B wins",Outcome==3~"Compromise",Outcome==4~"War transformed into another War",Outcome==5~"War ongoing as of end of 2014",Outcome==6~"Stalemate",Outcome==7~"Conflict continues below war level" ) )

IP$WarTypeD=ifelse(IP$WarType==4,'Civil War: Central Control',ifelse(IP$WarType==5,'Civil War: Local Issues',ifelse(IP$WarType%in%c(6,7),'Other','NA')))


#Create initiator deaths Var (need to create war id long dataset)
IP$InitiatorDeaths=ifelse(IP$Initiator==IP$SideA,IP$'Deaths A',IP$'Deaths B')
IP$RecipientDeaths=ifelse(IP$Initiator==IP$SideA,IP$'Deaths B',IP$'Deaths A')

#Set upper limit to deaths 50000
IP$TotalBDeathsU=ifelse(IP$TotalBDeaths>=50000,50000,IP$TotalBDeaths)

#Make Hemisphere driven variable
IP$Americas=ifelse(IP$V5Region %in% c(1,2),'Americas','Not in Americas')

#Let's make some dates

IP$Phase1_st=ymd( paste(IP$StartYr1, IP$StartMo1, IP$StartDy1, sep="-"))
IP$Phase2_st=ymd( paste(IP$StartYr2, IP$StartMo2, IP$StartDy2, sep="-"))
IP$Phase3_st=ymd( paste(IP$StartYr3, IP$StartMo3, IP$StartDy3, sep="-"))
IP$Phase4_st=ymd( paste(IP$StartYr4, IP$StartMo4, IP$StartDy4, sep="-"))

IP$Phase1_en=ymd( paste(IP$EndYr1, IP$EndMo1, IP$EndDy1, sep="-"))
IP$Phase2_en=ymd( paste(IP$EndYr2, IP$EndMo2, IP$EndDy2, sep="-"))
IP$Phase3_en=ymd( paste(IP$EndYr3, IP$EndMo3, IP$EndDy3, sep="-"))
IP$Phase4_en=ymd( paste(IP$EndYr4, IP$EndMo4, IP$EndDy4, sep="-"))


#Create output dataset


#glmer(TotalBDeaths ~ offset(log(WDuratDays)) + Americas +  + (1|stateID),
         #   family = poisson, data = LSss)





#Aim 2

library(mclust)
set.seed(3300)
fit.yr=Mclust(IP$StartYr1,G=2)
plot1.yr=plot(fit.yr$classification)
plot1.yr
dat1=data.frame(x=IP$StartYr1,class=factor(fit.yr$classification))
ggplot(dat1,aes(x,fill=class))+geom_histogram()




network_l=read_csv("derived_data/International.csv");

network_l$Initiator_side=ifelse(network_l$SideA==network_l$Initiator,network_l$Initiator,network_l$SideB)
network_l$Recipient_side=ifelse(network_l$SideB!=network_l$Initiator_side,network_l$SideB,network_l$SideA)
network_l$Initiator_side=ifelse(network_l$Initiator_side=='-8','NA',network_l$Initiator_side)
network_l$Recipient_side=ifelse(network_l$Recipient_side=='-8','NA',network_l$Recipient_side)


sources <- network_l %>%
  distinct(Initiator_side) %>%
  rename(label = Initiator_side)

destinations <-  network_l %>%
  distinct(Recipient_side) %>%
  rename(label = Recipient_side)


nodes <- full_join(sources, destinations, by = "label")
nodes

nodes <- nodes %>% rowid_to_column("id")

per_war <- network_l %>%  
  group_by(Initiator_side, Recipient_side) %>%
  mutate(weight = TotalBDeathsU) %>% 
  ungroup()
per_war

edges <- per_war %>% 
  left_join(nodes, by = c("Initiator_side" = "label")) %>% 
  rename(from = id)

edges <- edges %>% 
  left_join(nodes, by = c("Recipient_side" = "label")) %>% 
  rename(to = id)

edges2=select(edges, from, to, weight,Americas,Intnl)

library(network)
war_network <- network(edges2, vertex.attr = nodes, matrix.type = "edgelist", ignore.eval = FALSE)

plot(war_network, vertex.cex = 3,mode='circle')

detach(package:network)
rm(routes_network)
library(igraph)
library(RColorBrewer)

war_igraph <- graph_from_data_frame(d = edges2, vertices = nodes, directed = TRUE)

plot(war_igraph, edge.arrow.size = 0.2)

colrs <- c("gray50", "tomato")
V(war_igraph)$color <- colrs[V(war_igraph)$Americas]
plot(war_igraph, edge.arrow.size = 0.2)


plot(war_igraph)


pal <- brewer.pal(length(unique(V(war_igraph)$Americas)), "Dark2")

plot(war_igraph, vertex.color = pal[as.numeric(as.factor(vertex_attr(war_igraph, "group")))], layout=layout_randomly)

```
